export const SORT_ORDER_INCREMENT_COLLECTION = 1000;
export const SORT_ORDER_INCREMENT_TODO_ITEM = 1000;
export const AUTO_CLOSE_ERROR_TOAST = false;
export const AUTO_CLOSE_DEFAULT = 3000;
export const COLLECTION_SORT_ORDER_MAG = 1000;
