name: Playwright Tests

on:
  deployment_status:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release/** ]
    types: [ opened, reopened ]

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache && npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}